services:
  solana-validator:
    image: solanalabs/solana:stable
    command: solana-test-validator
    ports:
      - "8899:8899"
      - "8900:8900"
      - "8000-8009:8000-8009"
    networks:
      - solana-network
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

  solana-cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - solana-config:/root/.config/solana
    depends_on:
      - solana-validator
    networks:
      - solana-network
    env_file:
      - .env
    command: tail -f /dev/null
    ports:
      - "5173:5173"

volumes:
  solana-config:

networks:
  solana-network:
    driver: bridge