[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lockit = "CB81GRLWi7AjR6KDFawvbzfH3xQkCQh5YZznA7XzS7q6"

[programs.devnet]
lockit = "CB81GRLWi7AjR6KDFawvbzfH3xQkCQh5YZznA7XzS7q6"

[provider]
cluster = "devnet"  # должен быть devnet
wallet = "/app/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
